# Generated by Django 5.0.6 on 2024-07-03 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_portfolio_purchase_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
